In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [7]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
X_train

array([[ 0.3667663 , -1.49879627,  0.29532249, ..., -0.14803403,
        -0.92359108, -0.5159966 ],
       [-0.7378509 , -0.2791118 , -0.73816715, ..., -0.87947875,
        -1.10282398, -0.42521112],
       [-0.88571305,  0.46199171, -0.80922482, ...,  0.43972057,
         0.1069981 ,  0.66421466],
       ...,
       [-0.27686892, -1.28273788, -0.35470802, ..., -1.17819105,
        -1.26445364, -1.01088819],
       [-1.08576183, -1.65909765, -1.06780746, ..., -0.7001305 ,
         0.06379017, -0.37871124],
       [-1.02197816,  0.11583364, -1.02702288, ..., -0.69408675,
        -0.02262569, -0.36431842]])

In [9]:
y_train

209    B
304    B
41     M
427    B
223    M
      ..
133    B
476    B
309    B
390    B
245    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
y_train

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,

### Numpy arrays to PyTorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor.shape

torch.Size([455, 30])

In [14]:
y_train_tensor.shape

torch.Size([455])

In [15]:
# Define model
class mymodel:
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias= torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z=torch.matmul(X, self.weights) + self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


In [16]:
# modeling
model=mymodel(X_train_tensor)
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [17]:
# parameters
learning_rate=0.1
epochs=50

In [18]:
# model training

# loop
for epoch in range(epochs):

    # forward pass (wx+b and apply sigmoid)
    y_pred=model.forward(X_train_tensor)
    #print(y_pred)

    # loss calculation
    loss=model.loss_function(y_pred, y_train_tensor)
    #print(loss)
    
    # backward pass
    loss.backward()

    # parameters adjustments
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.848459796726477
Epoch: 2, Loss: 3.7295384349641463
Epoch: 3, Loss: 3.6048319397086828
Epoch: 4, Loss: 3.4776498951268042
Epoch: 5, Loss: 3.346983503665583
Epoch: 6, Loss: 3.2060758876864783
Epoch: 7, Loss: 3.054569645512207
Epoch: 8, Loss: 2.902595203919295
Epoch: 9, Loss: 2.7454447787768808
Epoch: 10, Loss: 2.584143992768056
Epoch: 11, Loss: 2.419026915221396
Epoch: 12, Loss: 2.247202753711894
Epoch: 13, Loss: 2.074715512783437
Epoch: 14, Loss: 1.9054487672502647
Epoch: 15, Loss: 1.738361566363243
Epoch: 16, Loss: 1.5788434125075328
Epoch: 17, Loss: 1.4312800945194124
Epoch: 18, Loss: 1.2974607660312594
Epoch: 19, Loss: 1.1774150558173173
Epoch: 20, Loss: 1.0727341010754057
Epoch: 21, Loss: 0.9866750929227889
Epoch: 22, Loss: 0.9191517607961978
Epoch: 23, Loss: 0.868677393793464
Epoch: 24, Loss: 0.8324908267101695
Epoch: 25, Loss: 0.8071637816897406
Epoch: 26, Loss: 0.789384008682351
Epoch: 27, Loss: 0.7765016361957712
Epoch: 28, Loss: 0.7666778560738262
Epoch: 29, L

In [19]:
model.bias 

tensor([-0.3057], dtype=torch.float64, requires_grad=True)

### Defining the model

In [20]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





### Important Parameters

In [21]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [22]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.308554963714097
Epoch: 2, Loss: 3.164268890545428
Epoch: 3, Loss: 3.018039732649314
Epoch: 4, Loss: 2.8632198491195586
Epoch: 5, Loss: 2.7040919607586154
Epoch: 6, Loss: 2.5397549702825732
Epoch: 7, Loss: 2.37312827783306
Epoch: 8, Loss: 2.2052613874674996
Epoch: 9, Loss: 2.0317495172354327
Epoch: 10, Loss: 1.8596690302789816
Epoch: 11, Loss: 1.6910221729873753
Epoch: 12, Loss: 1.529439059059267
Epoch: 13, Loss: 1.3793762474637519
Epoch: 14, Loss: 1.2423513972204177
Epoch: 15, Loss: 1.1235080509151298
Epoch: 16, Loss: 1.0245363610713207
Epoch: 17, Loss: 0.9460017193370716
Epoch: 18, Loss: 0.8869013579335311
Epoch: 19, Loss: 0.8446107102846337
Epoch: 20, Loss: 0.8154283358633999
Epoch: 21, Loss: 0.7955105227944378
Epoch: 22, Loss: 0.7816502510554985
Epoch: 23, Loss: 0.7715622003561482
Epoch: 24, Loss: 0.7637807009833039
Epoch: 25, Loss: 0.7574242674081609


In [23]:
model.bias

tensor([-0.1502], dtype=torch.float64, requires_grad=True)

### Evaluation

In [24]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6100338697433472
