In [146]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [147]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [148]:
df.shape

(569, 33)

In [149]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [150]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [151]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [152]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [153]:
X_train

array([[-0.88334823, -0.99987995, -0.85603512, ..., -0.1108089 ,
         0.61784993,  0.33325262],
       [-0.03053019,  1.82464443, -0.03370482, ..., -0.15197818,
        -1.05456539, -0.06839998],
       [-0.55534129, -0.2908525 , -0.57406968, ..., -0.40372069,
         0.48577526, -0.51873774],
       ...,
       [ 2.05730529, -0.96744078,  2.03018298, ...,  1.24777729,
        -0.29076011,  0.11416938],
       [-1.04592559, -0.15414459, -1.04745741, ..., -0.75457443,
        -1.11344205, -0.32188034],
       [-1.11152697, -0.62451248, -1.08921475, ..., -0.47935018,
        -0.35281929,  0.54439805]])

In [154]:
y_train

342    B
560    B
367    B
135    M
245    B
      ..
48     B
465    B
372    M
303    B
547    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [155]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [156]:
y_train

array([0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,

### Numpy arrays to PyTorch tensors

In [157]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [158]:
X_train_tensor.shape

torch.Size([455, 30])

In [159]:
y_train_tensor.shape

torch.Size([455])

In [160]:
# Define model
class mymodel:
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias= torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z=torch.matmul(X, self.weights) + self.bias
        y_pred=torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss


In [161]:
# modeling
model=mymodel(X_train_tensor)
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [162]:
# parameters
learning_rate=0.1
epochs=50

In [163]:
# model training

# loop
for epoch in range(epochs):

    # forward pass (wx+b and apply sigmoid)
    y_pred=model.forward(X_train_tensor)
    #print(y_pred)

    # loss calculation
    loss=model.loss_function(y_pred, y_train_tensor)
    #print(loss)
    
    # backward pass
    loss.backward()

    # parameters adjustments
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.4920467259225947
Epoch: 2, Loss: 3.353770239148589
Epoch: 3, Loss: 3.2115655153900384
Epoch: 4, Loss: 3.0634184318711566
Epoch: 5, Loss: 2.9119736468168305
Epoch: 6, Loss: 2.757331524807484
Epoch: 7, Loss: 2.601155171022183
Epoch: 8, Loss: 2.438414804127605
Epoch: 9, Loss: 2.2757976571537384
Epoch: 10, Loss: 2.110784214836244
Epoch: 11, Loss: 1.9435542442309455
Epoch: 12, Loss: 1.7799801204032044
Epoch: 13, Loss: 1.6232921985468334
Epoch: 14, Loss: 1.4785149790849048
Epoch: 15, Loss: 1.3476332320319013
Epoch: 16, Loss: 1.2325024384042451
Epoch: 17, Loss: 1.1345034351043393
Epoch: 18, Loss: 1.0541281867250203
Epoch: 19, Loss: 0.9906003089857536
Epoch: 20, Loss: 0.9418486703801024
Epoch: 21, Loss: 0.9050094741559593
Epoch: 22, Loss: 0.8771341255266435
Epoch: 23, Loss: 0.8556915205574911
Epoch: 24, Loss: 0.8387557968431938
Epoch: 25, Loss: 0.8249751312994251
Epoch: 26, Loss: 0.8134450849682247
Epoch: 27, Loss: 0.8035719377959761
Epoch: 28, Loss: 0.7949641124860264
Epoch:

In [169]:
model.bias 

tensor([-0.1295], dtype=torch.float64, requires_grad=True)

### Defining the model

In [164]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





### Important Parameters

In [165]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [166]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.0836750094855288
Epoch: 2, Loss: 2.9400199853649704
Epoch: 3, Loss: 2.7925036725349446
Epoch: 4, Loss: 2.6390464489884717
Epoch: 5, Loss: 2.4800856356053456
Epoch: 6, Loss: 2.3217663869299225
Epoch: 7, Loss: 2.163916843174521
Epoch: 8, Loss: 2.0094266734250144
Epoch: 9, Loss: 1.8539213683337243
Epoch: 10, Loss: 1.7012314687269519
Epoch: 11, Loss: 1.5590382567653631
Epoch: 12, Loss: 1.429014134567236
Epoch: 13, Loss: 1.3126789646352852
Epoch: 14, Loss: 1.2100838744144784
Epoch: 15, Loss: 1.120452071898182
Epoch: 16, Loss: 1.0466435768272908
Epoch: 17, Loss: 0.9853384669596797
Epoch: 18, Loss: 0.9376543529390754
Epoch: 19, Loss: 0.9012468674133308
Epoch: 20, Loss: 0.8736025624212655
Epoch: 21, Loss: 0.8524105188876199
Epoch: 22, Loss: 0.8357895570730745
Epoch: 23, Loss: 0.8223446081399057
Epoch: 24, Loss: 0.8111083617990521
Epoch: 25, Loss: 0.8014394860436205


In [167]:
model.bias

tensor([-0.1295], dtype=torch.float64, requires_grad=True)

### Evaluation

In [168]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6578947305679321
