### Forward pass 

In [ ]:
# Library
import torch
import torch.nn as nn

In [6]:
# Model architecture
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear=nn.Linear(num_features, 1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features) # y=wx+b
        out=self.sigmoid(out)
        return out

In [7]:
# Data
features=torch.rand(10, 5)
print(features)
print(features.shape)

# Creating model object
model=Model(features.shape[1])

# Calling model (forward pass)
model(features)

tensor([[0.6439, 0.5819, 0.0794, 0.7414, 0.2353],
        [0.7342, 0.2115, 0.3364, 0.9842, 0.9866],
        [0.4113, 0.6428, 0.6027, 0.1931, 0.0912],
        [0.9449, 0.7219, 0.1479, 0.1588, 0.5862],
        [0.7045, 0.3794, 0.0475, 0.1050, 0.5268],
        [0.4355, 0.9945, 0.8442, 0.8656, 0.2643],
        [0.5216, 0.2766, 0.6120, 0.3173, 0.3647],
        [0.9921, 0.5137, 0.5608, 0.3495, 0.6702],
        [0.8886, 0.6529, 0.7267, 0.2741, 0.4466],
        [0.1354, 0.9157, 0.4958, 0.9038, 0.4454]])
torch.Size([10, 5])


tensor([[0.6061],
        [0.5058],
        [0.6201],
        [0.5860],
        [0.5707],
        [0.6283],
        [0.5612],
        [0.5444],
        [0.5732],
        [0.6311]], grad_fn=<SigmoidBackward0>)

In [9]:
model.linear.bias

Parameter containing:
tensor([0.4127], requires_grad=True)

In [11]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Complex network

In [16]:
import torch
import torch.nn as nn

class Model_comp(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid(),
        )

    def forward(self,features):
        out=self.network(features)
        return out

In [22]:
features = torch.rand(10,5)
# print(features.shape)
# print(features)

model=Model_comp(features.shape[1])
model(features)

tensor([[0.4992],
        [0.4992],
        [0.4969],
        [0.4992],
        [0.4992],
        [0.4992],
        [0.4817],
        [0.4899],
        [0.4992],
        [0.5117]], grad_fn=<SigmoidBackward0>)

In [32]:
model.network[2].weight

Parameter containing:
tensor([[ 0.4985, -0.1719,  0.0005]], requires_grad=True)

In [33]:
from torchinfo import summary
summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model_comp                               [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00