Tensor is a data structure, multidimensional array.

In [2]:
import torch 

In [3]:
a1=torch.empty(2,3)
a1

tensor([[8.1344e-20, 2.0711e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [4]:
print(type(a1))
print(a1.shape)

<class 'torch.Tensor'>
torch.Size([2, 3])


In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.rand(2,3)

tensor([[0.2646, 0.4390, 0.6847],
        [0.2952, 0.9632, 0.2720]])

In [7]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [9]:
torch.linspace(1,10,50) 

tensor([ 1.0000,  1.1837,  1.3673,  1.5510,  1.7347,  1.9184,  2.1020,  2.2857,
         2.4694,  2.6531,  2.8367,  3.0204,  3.2041,  3.3878,  3.5714,  3.7551,
         3.9388,  4.1224,  4.3061,  4.4898,  4.6735,  4.8571,  5.0408,  5.2245,
         5.4082,  5.5918,  5.7755,  5.9592,  6.1429,  6.3265,  6.5102,  6.6939,
         6.8776,  7.0612,  7.2449,  7.4286,  7.6122,  7.7959,  7.9796,  8.1633,
         8.3469,  8.5306,  8.7143,  8.8980,  9.0816,  9.2653,  9.4490,  9.6327,
         9.8163, 10.0000])

In [10]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [11]:
torch.full((5,5), 7)

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]])

In [12]:
#datatype

In [29]:
t1=torch.tensor([10.0,11,0], dtype=float)
print(t1)
print(t1.dtype)

tensor([10., 11.,  0.], dtype=torch.float64)
torch.float64


In [30]:
t1.int()

tensor([10, 11,  0], dtype=torch.int32)

In [31]:
t1.bool()

tensor([ True,  True, False])