In [1]:
import torch

In [2]:
t1=torch.rand(3,3)
t1

tensor([[0.1288, 0.5231, 0.7229],
        [0.3873, 0.7539, 0.5514],
        [0.8515, 0.3823, 0.8152]])

In [3]:
t1+2

tensor([[2.1288, 2.5231, 2.7229],
        [2.3873, 2.7539, 2.5514],
        [2.8515, 2.3823, 2.8152]])

In [4]:
(t1*100)/3%2

tensor([[0.2943, 1.4374, 0.0979],
        [0.9106, 1.1298, 0.3800],
        [0.3848, 0.7437, 1.1724]])

In [5]:
t1

tensor([[0.1288, 0.5231, 0.7229],
        [0.3873, 0.7539, 0.5514],
        [0.8515, 0.3823, 0.8152]])

In [6]:
t2=torch.rand(3,3)
t2

tensor([[0.8149, 0.2102, 0.2926],
        [0.4001, 0.6519, 0.6873],
        [0.8785, 0.3976, 0.2584]])

In [7]:
t1+t2

tensor([[0.9437, 0.7333, 1.0155],
        [0.7875, 1.4058, 1.2387],
        [1.7300, 0.7799, 1.0735]])

In [8]:
t1**t2

tensor([[0.1883, 0.8727, 0.9094],
        [0.6842, 0.8318, 0.6642],
        [0.8683, 0.6823, 0.9486]])

In [9]:
t1%t2

tensor([[0.1288, 0.1027, 0.1378],
        [0.3873, 0.1020, 0.5514],
        [0.8515, 0.3823, 0.0400]])

In [10]:
t3=torch.tensor([1,2,-3,0])
t3

tensor([ 1,  2, -3,  0])

In [11]:
torch.abs(t3)

tensor([1, 2, 3, 0])

In [12]:
t4=torch.tensor([0.1,0.8,2.3,4.9])

In [13]:
torch.round(t4)

tensor([0., 1., 2., 5.])

In [14]:
torch.ceil(t4)

tensor([1., 1., 3., 5.])

In [15]:
torch.floor(t4)

tensor([0., 0., 2., 4.])

In [16]:
torch.clamp(t4,1,3)

tensor([1.0000, 1.0000, 2.3000, 3.0000])

In [17]:
# Reduction operation

In [18]:
t5=torch.randint(low=0,high=10, size=(3,3))
t5

tensor([[4, 7, 1],
        [7, 3, 5],
        [3, 5, 3]])

In [19]:
torch.sum(input=t5, dim=1)

tensor([12, 15, 11])

In [20]:
t6=t5.float()
torch.mean(input=t6, dim=1)

tensor([4.0000, 5.0000, 3.6667])

In [21]:
# Matrix operations

In [22]:
t7=torch.arange(start=0, end=6).reshape(2,3)
t8=torch.arange(start=6, end=12).reshape(3,2)
t8

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [23]:
t8.reshape(-1)

tensor([ 6,  7,  8,  9, 10, 11])

In [24]:
torch.matmul(input=t7, other=t8)

tensor([[ 28,  31],
        [100, 112]])

In [25]:
torch.dot(input=t7.reshape(-1),tensor=t8.reshape(-1))

tensor(145)

In [26]:
# comparision

In [27]:
t7

tensor([[0, 1, 2],
        [3, 4, 5]])

In [28]:
t8

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [29]:
t7>t8.reshape(2,3)

tensor([[False, False, False],
        [False, False, False]])

In [30]:
# Special 

In [31]:
t7

tensor([[0, 1, 2],
        [3, 4, 5]])

In [32]:
t9=torch.sqrt(t7)
t9

tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])

In [33]:
torch.sigmoid(t7)

tensor([[0.5000, 0.7311, 0.8808],
        [0.9526, 0.9820, 0.9933]])

In [34]:
torch.softmax(input=t9,dim=0)

tensor([[0.1503, 0.2689, 0.3054],
        [0.8497, 0.7311, 0.6946]])

In [35]:
t10=torch.tensor([1,0,-1,0.1])

In [36]:
torch.relu(input=t10)

tensor([1.0000, 0.0000, 0.0000, 0.1000])