In [1]:
import torch

In [8]:
t1=torch.rand(3,3)
t1

tensor([[0.1780, 0.6672, 0.7256],
        [0.2341, 0.2046, 0.8692],
        [0.2254, 0.2451, 0.9788]])

In [9]:
t1+2

tensor([[2.1780, 2.6672, 2.7256],
        [2.2341, 2.2046, 2.8692],
        [2.2254, 2.2451, 2.9788]])

In [11]:
(t1*100)/3%2

tensor([[1.9345, 0.2413, 0.1855],
        [1.8045, 0.8212, 0.9722],
        [1.5141, 0.1705, 0.6280]])

In [12]:
t1

tensor([[0.1780, 0.6672, 0.7256],
        [0.2341, 0.2046, 0.8692],
        [0.2254, 0.2451, 0.9788]])

In [14]:
t2=torch.rand(3,3)
t2

tensor([[0.5850, 0.1386, 0.3705],
        [0.3608, 0.4869, 0.3915],
        [0.5382, 0.2917, 0.8067]])

In [15]:
t1+t2

tensor([[0.7631, 0.8058, 1.0961],
        [0.5950, 0.6915, 1.2607],
        [0.7636, 0.5368, 1.7856]])

In [16]:
t1**t2

tensor([[0.3643, 0.9455, 0.8879],
        [0.5922, 0.4619, 0.9466],
        [0.4485, 0.6635, 0.9829]])

In [17]:
t1%t2

tensor([[0.1780, 0.1128, 0.3551],
        [0.2341, 0.2046, 0.0862],
        [0.2254, 0.2451, 0.1721]])

In [21]:
t3=torch.tensor([1,2,-3,0])
t3

tensor([ 1,  2, -3,  0])

In [23]:
torch.abs(t3)

tensor([1, 2, 3, 0])

In [24]:
t4=torch.tensor([0.1,0.8,2.3,4.9])

In [26]:
torch.round(t4)

tensor([0., 1., 2., 5.])

In [25]:
torch.ceil(t4)

tensor([1., 1., 3., 5.])

In [27]:
torch.floor(t4)

tensor([0., 0., 2., 4.])

In [28]:
torch.clamp(t4,1,3)

tensor([1.0000, 1.0000, 2.3000, 3.0000])

In [29]:
# Reduction operation

In [102]:
t5=torch.randint(low=0,high=10, size=(3,3))
t5

tensor([[3, 5, 2],
        [7, 8, 1],
        [7, 1, 8]])

In [66]:
torch.sum(input=t5, dim=1)

tensor([ 2, 10,  9])

In [70]:
t6=t5.float()
torch.mean(input=t6, dim=1)

tensor([0.6667, 3.3333, 3.0000])

In [71]:
# Matrix operations

In [91]:
t7=torch.arange(start=0, end=6).reshape(2,3)
t8=torch.arange(start=6, end=12).reshape(3,2)
t8

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [92]:
t8.reshape(-1)

tensor([ 6,  7,  8,  9, 10, 11])

In [80]:
torch.matmul(input=t7, other=t8)

tensor([[ 28,  31],
        [100, 112]])

In [93]:
torch.dot(input=t7.reshape(-1),tensor=t8.reshape(-1))

tensor(145)

In [103]:
# comparision

In [104]:
t7

tensor([[0, 1, 2],
        [3, 4, 5]])

In [105]:
t8

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [107]:
t7>t8.reshape(2,3)

tensor([[False, False, False],
        [False, False, False]])

In [109]:
# Special 

In [117]:
t7

tensor([[0, 1, 2],
        [3, 4, 5]])

In [119]:
t9=torch.sqrt(t7)
t9

tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])

In [112]:
torch.sigmoid(t7)

tensor([[0.5000, 0.7311, 0.8808],
        [0.9526, 0.9820, 0.9933]])

In [123]:
torch.softmax(input=t9,dim=0)

tensor([[0.1503, 0.2689, 0.3054],
        [0.8497, 0.7311, 0.6946]])

In [126]:
t10=torch.tensor([1,0,-1,0.1])

In [127]:
torch.relu(input=t10)

tensor([1.0000, 0.0000, 0.0000, 0.1000])