In [2]:
import torch

In [43]:
t1=torch.randint(size=(2,3), low=-10, high=10)
t2=torch.randint(size=(2,3), low=-10, high=10)
print(t1)
print(t2)

tensor([[-9,  4, -8],
        [-2,  0,  9]])
tensor([[ 0, -3,  2],
        [ 8,  1, -2]])


In [44]:
# t1.add(other=t2) # temp
t1.add_(other=t2) #in-place
t1

tensor([[-9,  1, -6],
        [ 6,  1,  7]])

In [45]:
print(torch.relu(t1)) #temp
print(t1)

tensor([[0, 1, 0],
        [6, 1, 7]])
tensor([[-9,  1, -6],
        [ 6,  1,  7]])


In [48]:
print(t1.relu_()) # in-place
print(t1)

tensor([[0, 1, 0],
        [6, 1, 7]])
tensor([[0, 1, 0],
        [6, 1, 7]])


In [1]:
import torch

In [2]:
t1= torch.tensor([1,2,3,4,5])
t1

tensor([1, 2, 3, 4, 5])

In [6]:
t1=torch.randint(-10, 10, (3,3))
t1

tensor([[ 3,  0,  1],
        [-5, -7, -1],
        [-7, -5, -8]])

In [10]:
t1.relu_()



tensor([[3, 0, 1],
        [0, 0, 0],
        [0, 0, 0]])

In [11]:
t1

tensor([[3, 0, 1],
        [0, 0, 0],
        [0, 0, 0]])