In [1]:
import torch

In [3]:
t1=torch.rand(4,4)
t1

tensor([[0.9325, 0.8089, 0.3423, 0.9657],
        [0.0457, 0.5548, 0.8519, 0.0861],
        [0.5726, 0.9126, 0.2669, 0.2535],
        [0.3247, 0.9887, 0.6183, 0.5401]])

In [6]:
t1.reshape(2,4,2)

tensor([[[0.9325, 0.8089],
         [0.3423, 0.9657],
         [0.0457, 0.5548],
         [0.8519, 0.0861]],

        [[0.5726, 0.9126],
         [0.2669, 0.2535],
         [0.3247, 0.9887],
         [0.6183, 0.5401]]])

In [8]:
t1.flatten()

tensor([0.9325, 0.8089, 0.3423, 0.9657, 0.0457, 0.5548, 0.8519, 0.0861, 0.5726,
        0.9126, 0.2669, 0.2535, 0.3247, 0.9887, 0.6183, 0.5401])

In [17]:
t2=torch.randint(low=0, high=256, size=(226,226,3))
print(t2.shape)

t2.unsqueeze_(0)
print(t2.shape)

torch.Size([226, 226, 3])
torch.Size([1, 226, 226, 3])


In [2]:
import torch

In [5]:
t3=torch.randint(-10,10,(3,3,3))
t3

tensor([[[  2,   5,  -6],
         [ -1,  -5,  -5],
         [  5,  -3,   3]],

        [[  9,   5,  -7],
         [  1,   7,   9],
         [ -8, -10,  -2]],

        [[-10,   9,   4],
         [ -7,   9,  -3],
         [ -7,   0,  -2]]])

In [9]:
t3.unsqueeze(3)

tensor([[[[  2],
          [  5],
          [ -6]],

         [[ -1],
          [ -5],
          [ -5]],

         [[  5],
          [ -3],
          [  3]]],


        [[[  9],
          [  5],
          [ -7]],

         [[  1],
          [  7],
          [  9]],

         [[ -8],
          [-10],
          [ -2]]],


        [[[-10],
          [  9],
          [  4]],

         [[ -7],
          [  9],
          [ -3]],

         [[ -7],
          [  0],
          [ -2]]]])