In [15]:
import numpy 
import torch

In [16]:
t=torch.rand(2,3)
t

tensor([[0.1988, 0.0592, 0.6424],
        [0.9056, 0.4163, 0.9495]])

In [17]:
t.numpy() # torch tensor to numpy array

array([[0.1987539 , 0.05915952, 0.64242655],
       [0.9055805 , 0.41625237, 0.94954276]], dtype=float32)

In [18]:
a=numpy.arange(start=0, stop=10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [19]:
torch.from_numpy(a) # numpy array to torch tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### torch vs numpy

In [20]:
import time
import jax.numpy as jnp

size=1200

#initialize
start_time = time.time()
t1=torch.randint(-100,100,(size, size))
t2=torch.randint(-100,100,(size, size))

mid_time=time.time()
print("initialization time: ", mid_time-start_time, "sec")

# multiplication
torch.matmul(input=t1, other=t2)

end_time=time.time()
print("torch multiplication time: ", end_time-mid_time, "sec")

#convert
a1=t1.numpy()
a2=t2.numpy()

arr_start=time.time()
print("conversion time: ", arr_start-end_time, "sec")

# multiplication
numpy.matmul(a1, a2)

end_a_time = time.time()
print("numpy multiplication time: ", end_a_time-arr_start, "sec")

#convert to jax
j1=jnp.array(a1)
j2=jnp.array(a2)

arr_start=time.time()
print("conversion time: ", arr_start-end_time, "sec")

# multiplication
jnp.matmul(j1, j2)

end_a_time = time.time()
print("jax multiplication time: ", end_a_time-arr_start, "sec")

initialization time:  0.04360389709472656 sec
torch multiplication time:  7.660017013549805 sec
conversion time:  0.0 sec
numpy multiplication time:  4.19208025932312 sec
conversion time:  4.222233533859253 sec
jax multiplication time:  0.13928580284118652 sec


In [24]:
import time
import torch
import numpy as np
import jax.numpy as jnp

# Matrix size
size = 1200

# ====================== Initialization ======================
start_time = time.time()

# Initialize random tensors in PyTorch
t1 = torch.randint(-100, 100, (size, size))
t2 = torch.randint(-100, 100, (size, size))

init_time = time.time()
print("Initialization time (PyTorch):", init_time - start_time, "sec")

# ====================== PyTorch Multiplication ======================
# Perform matrix multiplication in PyTorch
torch.matmul(t1, t2)

torch_time = time.time()
print("PyTorch multiplication time:", torch_time - init_time, "sec")

# ====================== Conversion to NumPy ======================
# Convert PyTorch tensors to NumPy arrays
a1 = t1.numpy()
a2 = t2.numpy()

conversion_time_numpy = time.time()
print("Conversion to NumPy time:", conversion_time_numpy - torch_time, "sec")

# ====================== NumPy Multiplication ======================
# Perform matrix multiplication in NumPy
np.matmul(a1, a2)

numpy_time = time.time()
print("NumPy multiplication time:", numpy_time - conversion_time_numpy, "sec")

# ====================== Conversion to JAX ======================
# Convert NumPy arrays to JAX arrays
j1 = jnp.array(a1)
j2 = jnp.array(a2)

conversion_time_jax = time.time()
print("Conversion to JAX time:", conversion_time_jax - numpy_time, "sec")

# ====================== JAX Multiplication ======================
# Perform matrix multiplication in JAX
jnp.matmul(j1, j2)

jax_time = time.time()
print("JAX multiplication time:", jax_time - conversion_time_jax, "sec")


Initialization time (PyTorch): 0.05354499816894531 sec
PyTorch multiplication time: 8.505818843841553 sec
Conversion to NumPy time: 0.0019516944885253906 sec
NumPy multiplication time: 4.5574791431427 sec
Conversion to JAX time: 0.011815786361694336 sec
JAX multiplication time: 0.14835262298583984 sec


In [29]:
numpy.matmul(t1, t2)
print("m")

jnp.matmul(a1, a2)
print("a")

m
a


C:\Users\Admin\AppData\Local\Temp\ipykernel_2280\256176021.py:1: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  numpy.matmul(t1, t2)
