In [105]:
# Autograd is used for calculating derivatives

In [106]:
# derivetive 1
def der_x(x):
    return x*2

y=der_x(5)
y

10

In [107]:
# derivative 2
import math
def der_x(x):
    return 2*x*math.cos(x**2)

y = der_x(2)
y

-2.6145744834544478

In [108]:
import torch

t1= torch.tensor([-50,-20,-3,-2,-1,0,1,2,3,20,50])
print(t1)
print(t1.sigmoid())

tensor([-50, -20,  -3,  -2,  -1,   0,   1,   2,   3,  20,  50])
tensor([1.9287e-22, 2.0612e-09, 4.7426e-02, 1.1920e-01, 2.6894e-01, 5.0000e-01,
        7.3106e-01, 8.8080e-01, 9.5257e-01, 1.0000e+00, 1.0000e+00])


In [109]:
# Training process:
# 1. Forward pass: Compute the ouput of the network given an input. {y=wx+b}
# 2. Calculate loss: Compute the loss function to quantify the error.
# 3. Backward pass: Compute gradient of the loss with respect to the parameters.
# 4. Update gradients: Adjust the parameters using an optimization algorithm. (e.g., gradient descent)

In [110]:
# derivative 1
t2=torch.tensor(3.0, requires_grad=True)
t2

tensor(3., requires_grad=True)

In [111]:
t3=t2**2
t3

tensor(9., grad_fn=<PowBackward0>)

In [112]:
t3.backward()

In [113]:
print(t2.grad)

tensor(6.)


In [114]:
# Derivative 2
t4=torch.tensor(3.0, requires_grad=True)
t5=t4**2
t6=torch.sin(t5)
t6

tensor(0.4121, grad_fn=<SinBackward0>)

In [115]:
t6.backward()


In [116]:
t4.grad

tensor(-5.4668)

### Forward pass (for scaler)

In [117]:
import numpy as np

def binary_cross_entropy_loss(y_true, y_pred):
    """
    Computes Binary Cross-Entropy Loss.

    Parameters:
    y_true (numpy array): Ground truth labels (0 or 1).
    y_pred (numpy array): Predicted probabilities (0 <= y_pred <= 1).

    Returns:
    float: Binary Cross-Entropy Loss.
    """
    # Ensure predicted values are in the range [0, 1]
    epsilon=1e-8
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)  # Avoid log(0) issues
    loss = -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
    return loss

In [118]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [119]:
w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

In [120]:
z=w*x+b 
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [121]:
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

### Loss calculation

In [122]:
l=binary_cross_entropy_loss(y, y_pred)
l

tensor(6.7012, grad_fn=<NegBackward0>)

### Backprop calculation

In [123]:
l.backward()

In [125]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [132]:
# Gradient for vector
a=torch.tensor([1.0,2.0,3.0], requires_grad=True)
a

b=(a**2).mean()
b

b.backward()
a.grad

tensor([0.6667, 1.3333, 2.0000])

In [134]:
# Clearing grad
a.grad.zero_()

tensor([0., 0., 0.])

In [135]:
# Disable gradient tracking
a.requires_grad_(False)

tensor([1., 2., 3.])

In [136]:
x=torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [137]:
with torch.no_grad():
    y=x**2    

In [138]:
y.backward() # gradient tracking is disabled

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn