### Tensor pass

In [59]:
import torch

def binary_cross_entropy_loss(y_true, y_pred):
    # Ensure predicted values are in the range [0, 1]
    epsilon=1e-8
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)  # Avoid log(0) issues
    loss = -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
    return loss


In [60]:
x=torch.tensor(5.5)
y=torch.tensor(0.0)

In [61]:
w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

In [62]:
# forward pass
z=w*x+b

In [63]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9959, grad_fn=<SigmoidBackward0>)

In [64]:
# loss calculation
loss=binary_cross_entropy_loss(y, y_pred)
loss

tensor(5.5041, grad_fn=<NegBackward0>)

In [65]:
# backward pass
loss.backward()

In [66]:
# gradient updates
print(w.grad) # gradient of the loss function w.r.t 'w'
print(b.grad) # dloss/db

tensor(5.4776)
tensor(0.9959)


In [67]:
lr=0.01
w=w-(lr*w.grad) # Gradient Descent
w

tensor(0.9452, grad_fn=<SubBackward0>)

In [1]:
import torch 

In [2]:
x=torch.tensor(6.6)
y=torch.tensor(0)

w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

In [3]:
def binary_cross_entropy_loss(y_true, y_pred):
    # Ensure predicted values are in the range [0, 1]
    epsilon=1e-8
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)  # Avoid log(0) issues
    loss = -(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred))
    return loss

In [5]:
# transformation
z=w*x+b
z

tensor(6.6000, grad_fn=<AddBackward0>)

In [ ]:
# forward pass
y_pred=torch.sigmoid(z)
y_pred

tensor(0.9986, grad_fn=<SigmoidBackward0>)

In [7]:
# loss calculation
loss_term=binary_cross_entropy_loss(y, y_pred)
loss_term

tensor(6.6013, grad_fn=<NegBackward0>)

In [8]:
#back propagartion
loss_term.backward()

In [10]:
w.grad # dl/dw

tensor(6.5910)

In [12]:
lr=0.1
w=w-(lr*w.grad)
w

tensor(0.3409, grad_fn=<SubBackward0>)

In [13]:
b.grad
b=b-(lr*b.grad)
b

tensor(-0.0999, grad_fn=<SubBackward0>)

In [14]:
z=w*x+b
z

tensor(2.1501, grad_fn=<AddBackward0>)

In [16]:
y_pred=torch.sigmoid(z)

In [17]:
loss_term=binary_cross_entropy_loss(y, y_pred)
loss_term

tensor(2.2602, grad_fn=<NegBackward0>)

### Image pass

In [ ]:
import torch
import torch.nn as nn

# Dummy image: 1 image, 1 channel, 28x28 size (like MNIST)
image = torch.randn(1, 1, 28, 28)

# Simple model: 1 conv layer + flatten + linear layer
model = nn.Sequential(
    nn.Conv2d(in_channels=1, out_channels=8, kernel_size=3),  # (1,28,28) -> (8,26,26)
    nn.ReLU(),
    nn.Flatten(),
    nn.Linear(8 * 26 * 26, 10)  # Output layer for 10 classes
)

# Forward pass
output = model(image)

print(output.shape)  # torch.Size([1, 10])

torch.Size([1, 10])


In [19]:
import torch
import torch.nn as nn

x=torch.rand(1,1,28,28)


In [21]:
model=nn.Sequential(
    nn.Conv2d(1, 8, 3), # (1,28,28) -> (8, 26,26)
    nn.ReLU(),
    nn.Flatten(), #(8*26*26)
    nn.Linear(8*26*26, 10) # (1,10)
)

In [23]:
obj=model(x)
obj.shape

torch.Size([1, 10])

In [69]:
import torch
import torch.nn as nn

In [70]:
image=torch.randn(1,1,28,28) # one image, one channel, 28x28 size

model=nn.Sequential(
    nn.Conv2d(in_channels=1, out_channels=8, kernel_size=3), # (1,28,28) -> (8,26,26)
    nn.ReLU(),
    nn.Flatten(),
    nn.Linear(8*26*26, 10)
)

In [ ]:
output=model(image)
print(output)

# output: tensor([[-0.0198, -0.1665,  0.0209,  0.0082, -0.0261, -0.2515,  0.1058, -0.0306, -0.1527,  0.0557]], grad_fn=<AddmmBackward0>)

tensor([[-0.0198, -0.1665,  0.0209,  0.0082, -0.0261, -0.2515,  0.1058, -0.0306,
         -0.1527,  0.0557]], grad_fn=<AddmmBackward0>)


In [ ]:
pred = torch.argmax(output, dim=1)
print(pred)  # e.g., tensor([3]) means class 3

tensor([6])


In [5]:
import torch
import torch.nn as nn

In [6]:
image=torch.randn(1,1,28,28)
# print(image)

model= nn.Sequential(
    nn.Conv2d(1,8,kernel_size=3), #(8, 26, 26)
    nn.ReLU(),
    nn.Flatten(),
    nn.Linear(8*26*26, 2)
)

output=model(image)
output

tensor([[0.0217, 0.2397]], grad_fn=<AddmmBackward0>)

In [14]:
x=torch.tensor(5.5)
y=torch.tensor(0.0)

w=torch.tensor(1.0, requires_grad=True)
b=torch.tensor(0.0, requires_grad=True)

In [15]:
z=w*x +b
z

tensor(5.5000, grad_fn=<AddBackward0>)

In [16]:
y_pred= nn.Sigmoid(z)
y_pred

TypeError: Sigmoid.__init__() takes 1 positional argument but 2 were given