In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import Rectangle
from skimage import measure

def overlay_mask_with_bounding_boxes(image_path, mask_path, output_file=None, alpha=0.5):
    """
    Load an image and a segmentation mask from NumPy files, overlay the mask on the image,
    and draw bounding boxes around segmented regions.
    
    Parameters:
    -----------
    image_path : str
        Path to the NumPy file containing the image
    mask_path : str
        Path to the NumPy file containing the segmentation mask
    output_file : str, optional
        Path to save the resulting visualization. If None, the image is not saved.
    alpha : float, optional
        Transparency of the mask overlay (0 to 1)
    """
    try:
        # Load the image and mask
        image = np.load(image_path)
        mask = np.load(mask_path)
        
        # Print information about the arrays
        print(f"Image shape: {image.shape}, dtype: {image.dtype}")
        print(f"Mask shape: {mask.shape}, dtype: {mask.dtype}")
        print(f"Mask unique values: {np.unique(mask)}")
        
        # Create a figure
        plt.figure(figsize=(12, 10))
        
        # Normalize image if needed (if not uint8 and values exceed 1)
        if image.dtype != np.uint8 and np.max(image) > 1:
            image_display = image / np.max(image)
        else:
            image_display = image.copy()
        
        # Display the image
        if len(image.shape) == 2:  # Grayscale
            plt.imshow(image_display, cmap='gray')
        else:  # Color image
            plt.imshow(image_display)
        
        # Overlay the mask
        mask_values = np.unique(mask)
        
        # Get the current axes for drawing boxes
        ax = plt.gca()
        
        # Process binary mask (values 0 and 255)
        if len(mask_values) == 2 and 0 in mask_values:
            # Find the non-zero value (typically 255 for binary masks)
            non_zero_value = [v for v in mask_values if v != 0][0]
            
            # Create a binary mask (1 for segment, 0 for background)
            binary_mask = (mask == non_zero_value).astype(np.uint8)
            
            # Label connected components in the mask
            labeled_mask, num_labels = measure.label(binary_mask, return_num=True)
            print(f"Found {num_labels} connected regions in the mask")
            
            # Create a masked array for visualization
            masked = np.ma.masked_where(mask == 0, mask)
            # Create a custom colormap with transparency for the first color
            mask_color = (1, 0, 0, 1)  # Red with full opacity
            custom_cmap = LinearSegmentedColormap.from_list('custom', [(0, 0, 0, 0), mask_color])
            plt.imshow(masked, cmap=custom_cmap, alpha=alpha, vmin=0, vmax=np.max(mask))
            
            # Find properties of labeled regions
            regions = measure.regionprops(labeled_mask)
            
            # Draw bounding boxes around each region
            for region in regions:
                # Get bounding box coordinates (min_row, min_col, max_row, max_col)
                minr, minc, maxr, maxc = region.bbox
                
                # Create a Rectangle patch
                rect = Rectangle((minc, minr), maxc - minc, maxr - minr,
                                fill=False, edgecolor='blue', linewidth=2)
                
                # Add the rectangle to the plot
                ax.add_patch(rect)
                
                # Optionally, add region number as label
                # plt.text(minc, minr - 5, f"R{region.label}", color='blue', fontsize=10)
        
        # For multi-class segmentation
        else:
            # Process each mask value separately
            for val in mask_values:
                if val == 0:  # Skip background
                    continue
                
                # Create a binary mask for this value
                binary_mask = (mask == val).astype(np.uint8)
                
                # Label connected components
                labeled_mask, num_labels = measure.label(binary_mask, return_num=True)
                print(f"Found {num_labels} connected regions for value {val}")
                
                # Mask overlay for this value
                masked = np.ma.masked_where(mask != val, mask)
                
                # Get a color for this class (using a colormap)
                cmap = plt.cm.get_cmap('tab10')
                color_idx = (val % 10) / 10.0  # Cycle through 10 colors
                color = cmap(color_idx)
                
                # Create custom colormap with transparency
                custom_cmap = LinearSegmentedColormap.from_list('custom', [(0, 0, 0, 0), color])
                plt.imshow(masked, cmap=custom_cmap, alpha=alpha, vmin=0, vmax=val)
                
                # Find regions
                regions = measure.regionprops(labeled_mask)
                
                # Draw boxes
                for region in regions:
                    minr, minc, maxr, maxc = region.bbox
                    rect = Rectangle((minc, minr), maxc - minc, maxr - minr,
                                    fill=False, edgecolor=color, linewidth=2)
                    ax.add_patch(rect)
        
          plt.title("Image with Segmentation Mask and Bounding Boxes")
          plt.axis('off')
          
          # Save the figure if output file is specified
          if output_file:
          
          plt.title("Image with Segmentation Mask Overlay")
          plt.axis('off')
          
          # Save the figure if output file is specified
          if output_file:
              plt.savefig(output_file, dpi=300, bbox_inches='tight')
              print(f"Visualization saved as '{output_file}'")
          
          plt.show()
          
      except Exception as e:
          print(f"Error processing the NumPy files: {e}")

# Example usage
if __name__ == "__main__":
    # Replace these with your actual file paths
    image_path = '/content/drive/MyDrive/Kites_projects/Clarity/Unet/easy_npy/images/3_0_bscan.npy'
    mask_path = '/content/drive/MyDrive/Kites_projects/Clarity/Unet/easy_npy/masks/3_0_mask.npy'
    output_file = 'image_mask_overlay.png'
    
    # You can adjust the alpha (transparency) if needed
    overlay_mask_with_bounding_boxes(image_path, mask_path, output_file, alpha=0.5)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 127)

In [ ]:
''' 
- **ANN (Artificial Neural Network)**:
  - Computational models inspired by biological neurons, used for classification and regression by learning complex, 
    nonlinear patterns.

- **Handling Image Data**:
  - Images are flattened into 1D arrays (pixels converted to input nodes), losing spatial relationships.

- **Why ANN isn't suitable for Image Data**:
  - Does **not preserve spatial context** (pixel proximity, position), reducing accuracy.
  - Inefficient compared to CNNs (Convolutional Neural Networks) which use spatial structures.

- **Scenarios Where ANN Outperforms Classical ML Models**:
  - Large datasets with **complex nonlinear patterns**.
  - Rich numerical data requiring complex feature interactions (high-dimensional tabular/statistical data).
  - Situations where classical ML models fail to capture intricate relationships effectively.
'''

In [ ]:
''' 
Difference between torch.tensor and torch.Tensor?
- torch.tensor() lets you explicitly set datatype; torch.Tensor() creates a default tensor of dtype float32.
'''

In [8]:
import torch
import torch.nn as nn

class ANN(nn.Module):
    def __init__(self):
        super().__init__()
        self.model=nn.Sequential(
            nn.Linear(3,5),
            nn.ReLU(),
            
            nn.Linear(5,1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)
    
model=ANN()
x=torch.tensor([1,2,3], dtype=torch.float32)
model(x)

# output: tensor([0.4941], grad_fn=<SigmoidBackward0>)

tensor([0.4118], grad_fn=<SigmoidBackward0>)

In [9]:
output = model(x)
loss = (output - torch.tensor([1.0]))**2  # dummy loss
loss.backward()  # gradients calculated here


In [ ]:
for param in model.parameters():
    print(param.grad)

''' 
tensor([[0.0000, 0.0000, 0.0000],
        [0.0516, 0.1032, 0.1547],
        [0.0041, 0.0081, 0.0122],
        [0.0000, 0.0000, 0.0000],
        [0.0388, 0.0776, 0.1163]])
tensor([0.0000, 0.0516, 0.0041, 0.0000, 0.0388])
tensor([[ 0.0000, -0.0853, -0.2087,  0.0000, -0.1173]])
tensor([-0.2850])
'''

tensor([[0.0000, 0.0000, 0.0000],
        [0.0516, 0.1032, 0.1547],
        [0.0041, 0.0081, 0.0122],
        [0.0000, 0.0000, 0.0000],
        [0.0388, 0.0776, 0.1163]])
tensor([0.0000, 0.0516, 0.0041, 0.0000, 0.0388])
tensor([[ 0.0000, -0.0853, -0.2087,  0.0000, -0.1173]])
tensor([-0.2850])
