In [ ]:
''' 
- **ANN (Artificial Neural Network)**:
  - Computational models inspired by biological neurons, used for classification and regression by learning complex, 
    nonlinear patterns.

- **Handling Image Data**:
  - Images are flattened into 1D arrays (pixels converted to input nodes), losing spatial relationships.

- **Why ANN isn't suitable for Image Data**:
  - Does **not preserve spatial context** (pixel proximity, position), reducing accuracy.
  - Inefficient compared to CNNs (Convolutional Neural Networks) which use spatial structures.

- **Scenarios Where ANN Outperforms Classical ML Models**:
  - Large datasets with **complex nonlinear patterns**.
  - Rich numerical data requiring complex feature interactions (high-dimensional tabular/statistical data).
  - Situations where classical ML models fail to capture intricate relationships effectively.
'''

In [ ]:
''' 
Difference between torch.tensor and torch.Tensor?
- torch.tensor() lets you explicitly set datatype; torch.Tensor() creates a default tensor of dtype float32.
'''

In [8]:
import torch
import torch.nn as nn

class ANN(nn.Module):
    def __init__(self):
        super().__init__()
        self.model=nn.Sequential(
            nn.Linear(3,5),
            nn.ReLU(),
            
            nn.Linear(5,1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.model(x)
    
model=ANN()
x=torch.tensor([1,2,3], dtype=torch.float32)
model(x)

# output: tensor([0.4941], grad_fn=<SigmoidBackward0>)

tensor([0.4118], grad_fn=<SigmoidBackward0>)

In [9]:
output = model(x)
loss = (output - torch.tensor([1.0]))**2  # dummy loss
loss.backward()  # gradients calculated here


In [ ]:
for param in model.parameters():
    print(param.grad)

''' 
tensor([[0.0000, 0.0000, 0.0000],
        [0.0516, 0.1032, 0.1547],
        [0.0041, 0.0081, 0.0122],
        [0.0000, 0.0000, 0.0000],
        [0.0388, 0.0776, 0.1163]])
tensor([0.0000, 0.0516, 0.0041, 0.0000, 0.0388])
tensor([[ 0.0000, -0.0853, -0.2087,  0.0000, -0.1173]])
tensor([-0.2850])
'''

tensor([[0.0000, 0.0000, 0.0000],
        [0.0516, 0.1032, 0.1547],
        [0.0041, 0.0081, 0.0122],
        [0.0000, 0.0000, 0.0000],
        [0.0388, 0.0776, 0.1163]])
tensor([0.0000, 0.0516, 0.0041, 0.0000, 0.0388])
tensor([[ 0.0000, -0.0853, -0.2087,  0.0000, -0.1173]])
tensor([-0.2850])
