In [1]:
import numpy as np

In [2]:
a1= np.array([1,2,3,4])
a2= np.array([4,5,6,7])

b1= np.arange(6).reshape(2,3)
b2= np.arange(6,12).reshape(2,3)
b2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
# Scalar operations
a1*2

array([2, 4, 6, 8])

In [4]:
# relational opp
a5=a2>5
a5
#print(a5.dtype)

array([False, False,  True,  True])

In [5]:
# vector operations
a1*a2

array([ 4, 10, 18, 28])

### Functions

In [6]:
np.max(a1)

np.int64(4)

In [7]:
np.sum(a1)

np.int64(10)

In [8]:
b1

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# 0-col, 1-row
np.max(b1, axis=1)

array([2, 5])

In [10]:
np.mean(a1)

np.float64(2.5)

In [11]:
b2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
b3=np.arange(12,18).reshape(3,2)
b3

array([[12, 13],
       [14, 15],
       [16, 17]])

In [13]:
np.dot(b3, b2)

array([[189, 214, 239],
       [219, 248, 277],
       [249, 282, 315]])

In [14]:
# round/ceil/floor


### indexing and slicing

In [15]:
x1=np.array([1,2,3,4])
x2=np.arange(10).reshape(5,2)
x3=np.arange(18).reshape(3,2,3)
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [16]:
x1[-1]

np.int64(4)

In [17]:
x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [18]:
x2[3,1]

np.int64(7)

In [19]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [20]:
x3[1][0][1]

np.int64(7)

In [21]:
x3[1,0,1]

np.int64(7)

In [22]:
# slicing

x1[1:3]

array([2, 3])

In [23]:
x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
x2[0,:]
x2[:,0]


array([0, 2, 4, 6, 8])

In [25]:
r=np.arange(9).reshape(3,3)
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
r[::2, ::2]

array([[0, 2],
       [6, 8]])

In [27]:
r[1, ::2]

array([3, 5])

In [28]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [29]:
#x3[::2]

In [30]:
x3[0, 1]

array([3, 4, 5])

In [31]:
x3[1, :, 1]

array([ 7, 10])

In [32]:
# Iterating

In [33]:
x1

array([1, 2, 3, 4])

In [34]:
for i in x1:
    print(i)

1
2
3
4


In [35]:
x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
for i in x2:
    print(i)

[0 1]
[2 3]
[4 5]
[6 7]
[8 9]


In [37]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [38]:
for i in x3:
    print(i)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]]


In [40]:
for i in np.nditer(x3):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 

In [41]:
# Reshape

In [42]:
x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
np.transpose(x2)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [44]:
x2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# Stacking (adding of vectors of same shape)

In [47]:
x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [56]:
x4=np.arange(10,20).reshape(5,2)
x4

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [57]:
np.hstack((x2, x4))

array([[ 0,  1, 10, 11],
       [ 2,  3, 12, 13],
       [ 4,  5, 14, 15],
       [ 6,  7, 16, 17],
       [ 8,  9, 18, 19]])

In [58]:
np.vstack((x2, x4))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [60]:
#splitting

In [64]:
np.hsplit(x2, 2)

[array([[0],
        [2],
        [4],
        [6],
        [8]]),
 array([[1],
        [3],
        [5],
        [7],
        [9]])]