In [2]:
import numpy as np

In [16]:
a1= np.array([1,2,3,4])
a2= np.array([4,5,6,7])

b1= np.arange(6).reshape(2,3)
b2= np.arange(6,12).reshape(2,3)
b2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
# Scalar operations
a1*2

array([2, 4, 6, 8])

In [13]:
# relational opp
a5=a2>5
a5
#print(a5.dtype)

array([False, False,  True,  True])

In [14]:
# vector operations
a1*a2

array([ 4, 10, 18, 28])

### Functions

In [17]:
np.max(a1)

np.int64(4)

In [18]:
np.sum(a1)

np.int64(10)

In [21]:
b1

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
# 0-col, 1-row
np.max(b1, axis=1)

array([2, 5])

In [22]:
np.mean(a1)

np.float64(2.5)

In [29]:
b2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
b3=np.arange(12,18).reshape(3,2)
b3

array([[12, 13],
       [14, 15],
       [16, 17]])

In [32]:
np.dot(b3, b2)

array([[189, 214, 239],
       [219, 248, 277],
       [249, 282, 315]])

In [ ]:
# round/ceil/floor


### indexing and slicing

In [37]:
x1=np.array([1,2,3,4])
x2=np.arange(10).reshape(5,2)
x3=np.arange(18).reshape(3,2,3)
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [38]:
x1[-1]

np.int64(4)

In [39]:
x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
x2[3,1]

np.int64(7)

In [41]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [44]:
x3[1][0][1]

np.int64(7)

In [45]:
x3[1,0,1]

np.int64(7)

In [51]:
# slicing

x1[1:3]

array([2, 3])

In [ ]:
x2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [55]:
x2[0,:]
x2[:,0]


array([0, 2, 4, 6, 8])

In [58]:
r=np.arange(9).reshape(3,3)
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
r[::2, ::2]

array([[0, 2],
       [6, 8]])

In [71]:
r[1, ::2]

array([3, 5])

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [75]:
x3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [82]:
#x3[::2]

In [80]:
x3[0, 1]

array([3, 4, 5])

In [90]:
x3[1, :, 1]

array([ 7, 10])