In [2]:
import numpy as np

In [ ]:
arr = np.array(4)
arr

array(4)

In [33]:
import numpy as np

# 1D array
a = np.array([1, 2, 3])
print("1D Array:", a,"data type",type(a[0]))

# 2D array
b = np.array([[1, 2], [3, 4]])
print("2D Array:", b)

# Array of zeros
c = np.zeros((2, 3))
print("Array of zeros (2x3):", c)

# Array of ones
d = np.ones((3))
print("Array of ones (3x3):", d,"data type",type(d[0]))

# Array with a range of values
e = np.arange(1, 10, 2)  # start, stop, step
print("Array with a range of values from 0 to 10 (step 2):", e)

# Linearly spaced values
f = np.linspace(0, 1, 5)  # start, stop, number of points
print("Linearly spaced values between 0 and 1 (5 points):", f)


1D Array: [1 2 3] data type <class 'numpy.int64'>
2D Array: [[1 2]
 [3 4]]
Array of zeros (2x3): [[0. 0. 0.]
 [0. 0. 0.]]
Array of ones (3x3): [1. 1. 1.] data type <class 'numpy.float64'>
Array with a range of values from 0 to 10 (step 2): [1 3 5 7 9]
Linearly spaced values between 0 and 1 (5 points): [0.   0.25 0.5  0.75 1.  ]


In [28]:
arr = np.array([10, 20, 30, 40, 50])

# Accessing elements
print("First element:", arr[0])  
print("Last element:", arr[-1]) 

# Slicing
print("Elements from index 1 to 3:", arr[1:4]) 
print("First three elements:", arr[:3])   
print("Every second element:", arr[1::2])  


First element: 10
Last element: 50
Elements from index 1 to 3: [20 30 40]
First three elements: [10 20 30]
Every second element: [20 40]


# basic operations

In [29]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Element-wise addition, subtraction, multiplication
print("Element-wise addition:", x + y)  
print("Element-wise subtraction:", x - y)  
print("Element-wise multiplication:", x * y)  

# Scalar operations
print("Multiply each element of x by 2:", x * 2)   

# Mathematical functions
print("Square root of each element in x:", np.sqrt(x))  
print("Sum of elements in x:", np.sum(x))  


Element-wise addition: [5 7 9]
Element-wise subtraction: [-3 -3 -3]
Element-wise multiplication: [ 4 10 18]
Multiply each element of x by 2: [2 4 6]
Square root of each element in x: [1.         1.41421356 1.73205081]
Sum of elements in x: 6


4. Shape and Reshaping
python
Copy code


In [48]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[10, 11, 12]])

# Shape of the array
print("Shape of the array:", arr.shape)  

# Reshape the array
reshaped = arr.reshape((4,3))
print("Array reshaped to 3x2:", reshaped)

# Flatten the array
flat = arr.flatten()
print("Flattened array:", flat)


Shape of the array: (4, 3)
Array reshaped to 3x2: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [50]:
# Random values between 0 and 1
rand = np.random.rand(3, 3)
print("Random array (values between 0 and 1):", rand)

# Random integers
rand_int = np.random.randint(0, 10, (2, 2))  # range, shape
print("Random integers (range 0 to 10):", rand_int)

# Normal distribution
rand_norm = np.random.randn(3)
print("Random values from a normal distribution:", rand_norm)


Random array (values between 0 and 1): [[0.14655968 0.36752952 0.58483276]
 [0.43438575 0.94382631 0.5076335 ]
 [0.71768662 0.50215194 0.81065898]]
Random integers (range 0 to 10): [[0 0]
 [9 2]]
Random values from a normal distribution: [1.84268225 1.11705116 0.52059377]
